import Cards from "./cards";
import data from "../data/img.json";
function CardsList() {
  return (
    <>
    <div className="container">
      <div>
        <Cards
          image={data[0].image}
          alt={data[0].alt}
          id={data[0].id}
          title={data[0].title}
          categorie={data[0].categorie}
          size={data[0].size}
          color={data[0].color}
          price={data[0].price}
        />
      </div>
      <div>
        <Cards
          image={data[1].image}
          alt={data[1].alt}
          id={data[1].id}
          title={data[1].title}
          categorie={data[1].categorie}
          size={data[1].size}
          color={data[1].color}
          price={data[1].price}
        />
      </div>
      <div>
        <Cards
          image={data[2].image}
          alt={data[2].alt}
          id={data[2].id}
          title={data[2].title}
          categorie={data[2].categorie}
          size={data[2].size}
          color={data[2].color}
          price={data[2].price}
        />
      </div>
      <div>
        <Cards
          image={data[3].image}
          alt={data[3].alt}
          id={data[3].id}
          title={data[3].title}
          categorie={data[3].categorie}
          size={data[3].size}
          color={data[3].color}
          price={data[3].price}
        />
      </div>
      <div>
        <Cards
          image={data[4].image}
          alt={data[4].alt}
          id={data[4].id}
          title={data[4].title}
          categorie={data[4].categorie}
          size={data[4].size}
          color={data[4].color}
          price={data[4].price}
        />
      </div>
      <div>
        <Cards
          image={data[5].image}
          alt={data[5].alt}
          id={data[5].id}
          title={data[5].title}
          categorie={data[5].categorie}
          size={data[5].size}
          color={data[5].color}
          price={data[5].price}
        />
      </div>
      <div>
        <Cards
          image={data[6].image}
          alt={data[6].alt}
          id={data[6].id}
          title={data[6].title}
          categorie={data[6].categorie}
          size={data[6].size}
          color={data[6].color}
          price={data[6].price}
        />
      </div>
      <div>
        <Cards
          image={data[7].image}
          alt={data[7].alt}
          id={data[7].id}
          title={data[7].title}
          categorie={data[7].categorie}
          size={data[7].size}
          color={data[7].color}
          price={data[7].price}
        />
      </div>
      <div>
        <Cards
          image={data[8].image}
          alt={data[8].alt}
          id={data[8].id}
          title={data[8].title}
          categorie={data[8].categorie}
          size={data[8].size}
          color={data[8].color}
          price={data[8].price}
        />
      </div>
      <div>
        <Cards
          image={data[9].image}
          alt={data[9].alt}
          id={data[9].id}
          title={data[9].title}
          categorie={data[9].categorie}
          size={data[9].size}
          color={data[9].color}
          price={data[9].price}
        />
      </div>
      </div>
    </>
  );
}

export default CardsList;
